alpineduo/alpineduo.github.io

- _posts/2020-07-04-ellmauer-halt-hike-20.md
> Add ellmauer halt hike

- _posts/2020-07-21-nesselcheibe-mtb-20.md
> add nesselscheibe mtb

- _posts/2020-08-12-gindelalm-mtb-20.md
> add gingelalm trails post

- _posts/2020-08-14-geierstein-mtb-20.md
> post: add geierstein

- _posts/2020-08-22-neureuth-trails-mtb-20.md
- _posts/2020-08-26-rohnberg-trails-mtb-20.md
> rohnberg mtb

- _posts/2020-09-05-rechelkopf-trail-mtb-20.md
> add rechelkopf mtb

- _posts/2020-09-10-wasenkogel-holzarm-trails-mtb-20.md
> add wasenkogel trail

- _posts/2020-08-27-ester-mountains-hike-20.md
> add ester mountains post

- _posts/2020-11-07-staufen-ridge-hike-20.md
> add hochstaufen hike

- _posts/2020-11-07-staufen-ridge-hike-20.md
> hochstaufen: fix resolution

- _posts/2020-11-14-bayerkarspitze-ridge-hike-20.md
> add bayerkarspitze

- _config.yml
> update instagram link

- _posts/2021-07-04-huberspitz-trails-mtb-21.md
> Add huberspitz

- _posts/2021-07-21-kampenwand-trails-mtb-21.md
> add kampenwand trails july 21

- _posts/2021-09-04-namlos-wetterspitze-weekend-hike-21.md
> add namlos hike weekend

- _config.yml
- _posts/2022-01-28-seekarkreuz-skitour.md
> Add seekarkreuz skitour

- _posts/2022-01-28-seekarkreuz-skitour.md
> fix seekarkreuz pics

- _posts/2021-09-13-mestia-hiking-getaway-21.md
> georgia: adding our 2 weeks in georgia getaway

- .github/workflows/build.yml
- .github/workflows/publish.yml
> github: Build jekyll with actions

- .github/workflows/publish.yml
I forgot to add source for jekyll page
> github: Fix source for the jekyll page

- .github/workflows/publish.yml
Use the pre build command to fix git safe dir
> github: Rervert back to the old way

- .github/workflows/publish.yml
It does not work, rather use our forked version
> github: Use forked version for deploy
